site_name: Nerdnode
repo_url: https://github.com/nerdnode-io/docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.select
    - content.code.copy
  language: en
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      enabled: !ENV [CI, false]
      repository: squidfunk/mkdocs-material
      branch: main

markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/vthGREn5

copyright: |
  &copy; 2023 <a href="https://github.com/nerdnode-io/"  target="_blank" rel="noopener">Nerdnode.io</a>